#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

use Sb\Command\CreateServiceCommand;

$application = new Application('service', '1.0.0');
$command = new CreateServiceCommand();

$application->add($command);

// $application->setDefaultCommand($command->getName(), true);
$application->run();

